library(kknn)
data(iris)
val <- sample(1:dim(iris)[1], size = round(dim(iris)[1]/3), replace = FALSE, prob = rep(1/dim(iris)[1], dim(iris)[1])) 
iris.kknn <- train.kknn(Species~., iris[-val,], distance = 1, kernel = c("triangular", "epanechnikov", "biweight", "triweight", "cos", "inv", "gaussian", "rank", "optimal") )
summary(iris.kknn)
table(predict(iris.kknn,iris[val,]),iris[val,]$Species)
str(iris.kknn)
head(iris.kknn$fitted.values[[1]])
head(iris.kknn$fitted.values)
