library(rpart)
library(party)
library(cluster)
data(Titanic)
rpart_model <- rpart(Survived ~ ., data = as.data.frame(Titanic), method = "class")
ctree_model <- ctree(Survived ~ ., data = as.data.frame(Titanic))
plot(rpart_model)
text(rpart_model, use.n = TRUE)
plot(ctree_model)
plot(hclust(dist(scale(as.data.frame(Titanic)[, sapply(as.data.frame(Titanic), is.numeric)]))))
groups <- cutree(hclust(dist(scale(as.data.frame(Titanic)[, sapply(as.data.frame(Titanic), is.numeric)]))), k = 5)
