class(fit2M)
fit2M <- ctree(Mileage~Price + Country + Reliability + Type, data=na.omit(cu.summary))
summary(fit2M)
plot(fit2M, uniform=TRUE, main="CI Tree Tree for Mileage ")
plot(fit2M, tp_args = list(cex = 0.8))